import React from "react";

// FULLY GENERATED BY AI
class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false, error: null };
  }

  static getDerivedStateFromError(error) {
    return { hasError: true, error };
  }

  componentDidCatch(error, errorInfo) {
    console.error("Error caught by ErrorBoundary:", error, errorInfo);
  }

  handleReset = () => {
    this.setState({ hasError: false, error: null });
    window.location.reload();
  };

  render() {
    if (this.state.hasError) {
      return (
        <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-pink-100 via-blue-100 to-purple-100 px-4">
          <div className="max-w-md w-full rounded-3xl bg-white/80 backdrop-blur shadow-xl p-8 text-center border border-pink-200">
            
            <div className="text-6xl mb-4">૮ ˶ᵔ ᵕ ᵔ˶ ა</div>

            <h1 className="text-2xl font-bold text-pink-500 mb-2">
              Oopsie~
            </h1>

            <p className="text-gray-600 text-sm mb-6">
              Kayaknya aplikasinya lagi error nih… perbaiki dulu yaa~ 🌸
            </p>

            <div className="bg-pink-50 text-pink-600 text-xs rounded-xl p-3 mb-6 overflow-auto max-h-24">
              {this.state.error?.message}
            </div>

            <button
              onClick={this.handleReset}
              className="px-6 py-2 rounded-full bg-pink-400 hover:bg-pink-500 text-white font-medium transition-all shadow-md"
            >
              Restart ✨
            </button>

          </div>
        </div>
      );
    }

    return this.props.children;
  }
}

export default ErrorBoundary;